/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    AddIcon: typeof import('./components/icons/AddIcon.vue')['default']
    ArrowBackIcon: typeof import('./components/icons/ArrowBackIcon.vue')['default']
    ArrowRightIcon: typeof import('./components/icons/ArrowRightIcon.vue')['default']
    ChatMessage: typeof import('./components/ChatMessage.vue')['default']
    ChatMessageList: typeof import('./components/ChatMessageList.vue')['default']
    ChatSidebar: typeof import('./components/ChatSidebar.vue')['default']
    ChatSidebarItem: typeof import('./components/ChatSidebarItem.vue')['default']
    ChatTextArea: typeof import('./components/ChatTextArea.vue')['default']
    CheckedIcon: typeof import('./components/icons/CheckedIcon.vue')['default']
    CloseIcon: typeof import('./components/icons/CloseIcon.vue')['default']
    DarkIcon: typeof import('./components/icons/DarkIcon.vue')['default']
    DeleteIcon: typeof import('./components/icons/DeleteIcon.vue')['default']
    InfoIcon: typeof import('./components/icons/InfoIcon.vue')['default']
    Layout: typeof import('./components/Layout.vue')['default']
    LightIcon: typeof import('./components/icons/LightIcon.vue')['default']
    LocalesIcon: typeof import('./components/icons/localesIcon.vue')['default']
    MemoryIcon: typeof import('./components/icons/MemoryIcon.vue')['default']
    MessageIcon: typeof import('./components/icons/MessageIcon.vue')['default']
    ModeIcon: typeof import('./components/icons/ModeIcon.vue')['default']
    NAlert: typeof import('naive-ui')['NAlert']
    Navbar: typeof import('./components/Navbar.vue')['default']
    NButton: typeof import('naive-ui')['NButton']
    NDialogProvider: typeof import('naive-ui')['NDialogProvider']
    NEllipsis: typeof import('naive-ui')['NEllipsis']
    NForm: typeof import('naive-ui')['NForm']
    NFormItem: typeof import('naive-ui')['NFormItem']
    NH2: typeof import('naive-ui')['NH2']
    NH5: typeof import('naive-ui')['NH5']
    NIcon: typeof import('naive-ui')['NIcon']
    NInput: typeof import('naive-ui')['NInput']
    NMessageProvider: typeof import('naive-ui')['NMessageProvider']
    NPopover: typeof import('naive-ui')['NPopover']
    NRadioButton: typeof import('naive-ui')['NRadioButton']
    NRadioGroup: typeof import('naive-ui')['NRadioGroup']
    NSelect: typeof import('naive-ui')['NSelect']
    NSpace: typeof import('naive-ui')['NSpace']
    OpenAIIcon: typeof import('./components/icons/OpenAIIcon.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SendIcon: typeof import('./components/icons/SendIcon.vue')['default']
    SettingForm: typeof import('./components/SettingForm.vue')['default']
    SettingIcon: typeof import('./components/icons/SettingIcon.vue')['default']
    UserIcon: typeof import('./components/icons/UserIcon.vue')['default']
  }
}
